spring:
  application:
    name: loop-api

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true # false in prod
    generate-ddl: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379


server:
  servlet:
    context-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,scheduledtasks

springdoc:
  api-docs:
    path: /docs/api-docs
  swagger-ui:
    path: /docs/swagger-ui.html

app:
  base-url: ${BASE_URL}
  verification:
    token-expiration-hours: 24

jwt:
  secret: ${JWT_SECRET}
  accessExpirationMs: ${JWT_ACCESS_EXPIRATION_MS}
  refreshExpirationMs: ${JWT_REFRESH_EXPIRATION_MS}

logging:
  level:
    root: INFO