name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      # Run unit tests on ALL pushes and PRs
      - name: Run unit tests
        run: ./mvnw clean test -Dgroups=UnitTest

      # Run full test suite with coverage on main push or PRs
      - name: Run all tests with coverage (main)
        if: github.ref == 'refs/heads/main'
        run: ./mvnw clean verify

      # Upload test coverage to Codecov (main only)
      - name: Upload coverage to Codecov
        if: github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      # Store test results as artifacts
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            target/surefire-reports/
            target/failsafe-reports/
            target/site/jacoco/